'use client';
import { useCallback,useEffect,useMemo,useState } from 'react';
import { ArrowUpRight,Check,Clock,DollarSign,LoaderCircle,RefreshCw,Sparkles,WalletCards } from 'lucide-react';
import { addonsForAudience,plansForAudience,type MonetizationAudience,type MonetizationPlan,type MonetizationAddOn } from '@/lib/monetization-catalog';
import type { Locale } from '@/lib/i18n-shared';

type Props={locale?:Locale;role:'BUYER'|'MANUFACTURER'};
async function json(r:Response){const tx=await r.text();try{return tx?JSON.parse(tx):{}}catch{return{error:tx}}}
const fmt=(v:any,c='EUR',locale:Locale='hu')=>{const n=Number(v);if(!Number.isFinite(n))return'—';try{return new Intl.NumberFormat(locale==='en'?'en-GB':'hu-HU',{style:'currency',currency:c,maximumFractionDigits:2}).format(n)}catch{return`${n} ${c}`}};
const planPrice=(plan:MonetizationPlan,offer:any,yearly:boolean,locale:Locale)=>{let value=yearly?(offer?.metadata?.yearly??plan.priceYearly):(offer?.price??plan.priceMonthly);if(value===null||value===undefined)return locale==='en'?'Custom':'Egyedi';value=Number(value);if(value===0)return locale==='en'?'Free':'Ingyenes';return `${new Intl.NumberFormat(locale==='en'?'en-GB':'hu-HU').format(value)} €${yearly?(locale==='en'?'/year':'/év'):(locale==='en'?'/month':'/hó')}`};
const addonPrice=(addon:MonetizationAddOn,offer:any,locale:Locale)=>{const value=offer?.price??addon.price;if(value===null||value===undefined)return locale==='en'?'Custom':'Egyedi';return fmt(value,offer?.currency||addon.currency,locale)};
export default function BillingPortalClient({locale='hu',role}:Props){const en=locale==='en',t=(hu:string,e:string)=>en?e:hu;const[data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[msg,setMsg]=useState(''),[err,setErr]=useState(''),[yearly,setYearly]=useState(false);const load=useCallback(async()=>{setLoading(true);setErr('');const r=await fetch('/api/billing/me',{cache:'no-store'});const d=await json(r);if(r.ok)setData(d);else setErr(d.error||t('Billing betöltési hiba.','Billing load failed.'));setLoading(false)},[en]);useEffect(()=>{void load()},[load]);const state=data?.state;const audiences:MonetizationAudience[]=useMemo(()=>{if(role==='BUYER')return['BUYER'];if(state?.supplierType==='BOTH')return['MANUFACTURER','WHOLESALER'];return[state?.audience||'MANUFACTURER']},[role,state?.audience,state?.supplierType]);const plans=audiences.flatMap(a=>plansForAudience(a));const addons=Array.from(new Map(audiences.flatMap(a=>addonsForAudience(a)).map(x=>[x.code,x])).values());const offersByCode=useMemo(()=>new Map((data?.offers||[]).map((x:any)=>[x.code,x])),[data?.offers]);async function requestOffer(code:string){setBusy(code);setErr('');setMsg('');const r=await fetch('/api/billing/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({offer_code:code,billing_cycle:yearly?'YEARLY':'MONTHLY'})});const d=await json(r);if(r.ok){setMsg(t('A kérelmet elküldtük. Az admin jóváhagyás és számlázás után aktiválja.','Request submitted. The admin will activate it after approval and billing.'));await load()}else setErr(d.error||t('A kérelem sikertelen.','Request failed.'));setBusy('')}
 if(loading)return <div className="empty-state"><LoaderCircle className="spin"/></div>;
 const usage=state?.usage||{};const ent=state?.entitlements||{};const credits=state?.credits||{};return <div className="platform-stack">
  <section className="billing-current"><div><p className="eyebrow">{t('AKTUÁLIS CSOMAG','CURRENT PLAN')}</p><div className="billing-plan-title"><h2>{state?.plan?.[en?'nameEn':'nameHu']||state?.planCode}</h2><span>{state?.planCode}</span></div><p>{state?.plan?.[en?'descriptionEn':'descriptionHu']||''}</p></div><div className="billing-current-actions"><div className="billing-cycle"><button className={!yearly?'active':''} onClick={()=>setYearly(false)}>{t('Havi','Monthly')}</button><button className={yearly?'active':''} onClick={()=>setYearly(true)}>{t('Éves','Yearly')} <small>-2 {t('hó','months')}</small></button></div><button className="icon-button" onClick={()=>void load()} aria-label={t('Frissítés','Refresh')}><RefreshCw size={17}/></button></div></section>
  {err&&<div className="run-error">{err}</div>}{msg&&<div className="run-report">{msg}</div>}
  <section className="portal-stat-grid billing-usage-grid">{role==='BUYER'?<><article><span>{t('Csomagszint','Plan tier')}</span><strong>{state?.planCode||'BUYER_FREE'}</strong></article><article><span>{t('Csapathelyek','Team seats')}</span><strong>{ent.teamSeats==null?'∞':ent.teamSeats}</strong></article><article><span>{t('Riport export','Report export')}</span><strong>{ent.exportTools?t('Igen','Yes'):t('Nem','No')}</strong></article><article><span>{t('Standard tranzakciós díj','Standard transaction fee')}</span><strong>{ent.successFeePct??'—'}%</strong></article></>:<><article><span>{t('Aktív Group Order','Active Group Orders')}</span><strong>{usage.activeGroupOrders||0} / {ent.activeGroupOrders==null?'∞':ent.activeGroupOrders}</strong></article><article><span>{t('Boost kreditek','Boost credits')}</span><strong>{credits.BOOST||ent.monthlyBoostCredits||0}</strong></article><article><span>{t('Buyer demand kreditek','Buyer-demand credits')}</span><strong>{credits.LEAD||ent.monthlyLeadCredits||0}</strong></article><article><span>{t('Group Order díj','Group Order fee')}</span><strong>{ent.groupOrderFeePct??'—'}%</strong></article></>}</section>
  <section><div className="section-heading compact-heading"><div><p className="eyebrow">{t('ELŐFIZETÉSEK','SUBSCRIPTIONS')}</p><h2>{t('Válassz növekedési csomagot','Choose a growth plan')}</h2></div><p>{t('A csomagváltás jelenleg kérelmi + admin jóváhagyási folyamat. Így a prototípus már tesztelhető valódi kereskedelmi ajánlatokkal fizetési szolgáltató bekötése nélkül.','Plan changes currently use a request + admin approval flow, so the prototype can validate real commercial offers before a payment provider is connected.')}</p></div><div className="pricing-grid monetization-plan-grid">{plans.map(plan=>{const current=state?.planCode===plan.code;return <article className={plan.featured?'featured':''} key={plan.code}><div className="plan-card-top"><span>{plan.audience}</span>{current&&<b>{t('AKTUÁLIS','CURRENT')}</b>}</div><h2>{en?plan.nameEn:plan.nameHu}</h2><strong className="plan-price">{planPrice(plan,offersByCode.get(plan.code),yearly,locale)}</strong><p>{en?plan.descriptionEn:plan.descriptionHu}</p><ul>{(en?plan.featuresEn:plan.featuresHu).map(f=><li key={f}><Check size={15}/>{f}</li>)}</ul><button className={plan.featured?'button button-light':'button'} disabled={current||busy!==''} onClick={()=>void requestOffer(plan.code)}>{busy===plan.code?<LoaderCircle className="spin" size={17}/>:<ArrowUpRight size={17}/>} {current?t('Aktív csomag','Current plan'):(plan.priceMonthly==null?t('Egyedi ajánlat','Request quote'):t('Csomag igénylése','Request plan'))}</button></article>})}</div></section>
  <section className="manufacturer-panel"><div className="manufacturer-toolbar"><div><strong>{t('Kiegészítő fizetős szolgáltatások','Paid add-ons & services')}</strong><small>{t('Egyszeri szolgáltatás, kreditek, kiemelések és szponzorált megjelenések.','One-off services, credits, boosts and sponsored placements.')}</small></div><Sparkles size={20}/></div><div className="addon-grid">{addons.filter(a=>!['SUCCESS_FEE','GROUP_ORDER_TRANSACTION_FEE'].includes(a.code)).map(a=><article key={a.code}><div><span>{a.period.replace('_',' ')}</span><h3>{en?a.nameEn:a.nameHu}</h3><p>{en?a.descriptionEn:a.descriptionHu}</p></div><div className="addon-price"><strong>{addonPrice(a,offersByCode.get(a.code),locale)}</strong><button className="button button-small" disabled={busy!==''} onClick={()=>void requestOffer(a.code)}>{busy===a.code?<LoaderCircle className="spin" size={15}/>:<DollarSign size={15}/>} {t('Igénylem','Request')}</button></div></article>)}</div></section>
  <section className="billing-history-grid"><article className="manufacturer-panel"><h3>{t('Kérelmek','Requests')}</h3>{(data?.requests||[]).length===0?<div className="empty-state">{t('Nincs még kérelmed.','No requests yet.')}</div>:<div className="billing-list">{data.requests.map((r:any)=><div key={r.id}><Clock size={15}/><span><strong>{r.offer_code}</strong><small>{new Date(r.created_at).toLocaleString(en?'en-GB':'hu-HU')}</small></span><b className={`group-status status-${String(r.status).toLowerCase()}`}>{r.status}</b></div>)}</div>}</article><article className="manufacturer-panel"><h3>{t('Díjak / számlázási ledger','Charges / billing ledger')}</h3>{(data?.ledger||[]).length===0?<div className="empty-state">{t('Még nincs rögzített díj.','No charges recorded yet.')}</div>:<div className="billing-list">{data.ledger.map((r:any)=><div key={r.id}><WalletCards size={15}/><span><strong>{r.description||r.source_type}</strong><small>{r.status}</small></span><b>{fmt(r.amount,r.currency,locale)}</b></div>)}</div>}</article></section>
 </div>}
