'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState, type ChangeEvent, type FormEvent } from 'react';
import { Crown, LoaderCircle, Plus, RefreshCw, ShoppingCart } from 'lucide-react';
import GroupOrderProgress from './GroupOrderProgress';
import { displayUnit, formatMoney, formatQuantity, type GroupOrderView } from '@/lib/group-orders';
import type { Locale } from '@/lib/i18n-shared';

type ApiData = { error?: string; group_orders?: GroupOrderView[]; commercial?: any; upgrade_required?: boolean };
type FormState = { title:string;brand:string;product_name:string;product_description:string;category:string;supplier_url:string;moq_label:string;target_quantity:string;unit:string;min_join_quantity:string;unit_price:string;price_unit:string;price_units_per_order_unit:string;currency:string;destination_country:string;deadline:string;notes:string };
const initialForm:FormState={title:'',brand:'',product_name:'',product_description:'',category:'Háztartási és FMCG',supplier_url:'',moq_label:'',target_quantity:'',unit:'raklap',min_join_quantity:'1',unit_price:'',price_unit:'karton',price_units_per_order_unit:'1',currency:'EUR',destination_country:'Magyarország',deadline:'',notes:''};
async function responseData(response:Response):Promise<ApiData>{const text=await response.text();if(!text)return{};try{return JSON.parse(text)as ApiData}catch{return{error:text}}}

export default function ManufacturerGroupOrdersClient({locale='hu'}:{locale?:Locale}){
 const en=locale==='en',t=(hu:string,eng:string)=>en?eng:hu;const[items,setItems]=useState<GroupOrderView[]>([]),[commercial,setCommercial]=useState<any>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[form,setForm]=useState<FormState>(initialForm);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const response=await fetch(`/api/supplier/group-orders?locale=${locale}`,{cache:'no-store'});const data=await responseData(response);if(!response.ok)throw new Error(data.error||t('Az ajánlatok betöltése sikertelen.','Failed to load offers.'));setItems(data.group_orders||[]);setCommercial(data.commercial||null)}catch(e){setError(e instanceof Error?e.message:t('Betöltési hiba.','Load failed.'))}finally{setLoading(false)}},[locale,en]);useEffect(()=>{void load()},[load]);
 async function requestBoost(groupOrderId:string){setError('');setMessage('');const response=await fetch('/api/billing/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({offer_code:'GROUP_ORDER_BOOST_7D',quantity:1,metadata:{group_order_id:groupOrderId}})});const data=await responseData(response);if(response.ok)setMessage(t('A 7 napos kampánykiemelés kérelme elküldve. Admin jóváhagyás után aktiválódik.','The 7-day campaign boost request was submitted. It activates after admin approval.'));else setError(data.error||t('A boost igénylése sikertelen.','Boost request failed.'))}
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/supplier/group-orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await responseData(response);if(!response.ok)throw new Error(data.error||(data.upgrade_required?t('A csomag Group Order limitje elfogyott.','Your plan Group Order limit has been reached.'):t('Az ajánlat mentése sikertelen.','Failed to save the offer.')));setForm({...initialForm,category:en?'Household & FMCG':'Háztartási és FMCG',unit:en?'pallet':'raklap',price_unit:en?'carton':'karton',destination_country:en?'Hungary':'Magyarország'});setMessage(t('Az ajánlatot elküldtük admin-ellenőrzésre. Jóváhagyás után megjelenik a vevőknek.','The offer was submitted for admin review. It will become visible to buyers after approval.'));await load()}catch(e){setError(e instanceof Error?e.message:t('Mentési hiba.','Save failed.'))}finally{setBusy(false)}}
 const change=(key:keyof FormState)=>(event:ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>setForm({...form,[key]:event.target.value});
 const limit=commercial?.entitlements?.activeGroupOrders;const used=commercial?.usage?.activeGroupOrders||0;
 return <>
  <section className="commercial-note group-plan-note"><div><Crown size={17}/><strong>{t('Aktuális csomag','Current plan')}: {commercial?.planCode||'—'}</strong></div><span>{t('Aktív Group Order','Active Group Orders')}: {used} / {limit==null?'∞':limit} · {t('Tranzakciós díj','Transaction fee')}: {commercial?.entitlements?.groupOrderFeePct??'—'}%</span><Link href="/supplier/billing">{t('Csomagok és boostok','Plans & boosts')} →</Link></section>
  <form className="portal-form compact-form" onSubmit={create}><div className="group-form-title"><div><p className="eyebrow">{t('ÚJ BESZÁLLÍTÓI MOQ AJÁNLAT','NEW SUPPLIER MOQ OFFER')}</p><h2>{t('Adj meg egy fix árat és egy fix MOQ-t','Set one fixed price and one fixed MOQ')}</h2></div><ShoppingCart size={36}/></div><p className="group-form-note">{t('Gyártók, importőrök és nagykereskedők fix árú, magas MOQ-s ajánlatai admin-ellenőrzés után nyílnak meg a vevőknek. Az ár a kampány telítettségével nem változik.','Fixed-price high-MOQ offers from manufacturers, importers and wholesalers are opened to buyers after admin review. The price does not change as the campaign fills.')}</p>
   <div className="form-grid">
    <label>{t('Ajánlat címe','Offer title')}<input required value={form.title} onChange={change('title')} placeholder={t('pl. Coccolino kétkamionos közös rendelés','e.g. Coccolino two-truck pooled order')}/></label>
    <label>{t('Márka','Brand')}<input value={form.brand} onChange={change('brand')} placeholder="Coccolino"/></label>
    <label>{t('Termék','Product')}<input required value={form.product_name} onChange={change('product_name')} placeholder={t('Coccolino öblítő 1,7 l','Coccolino fabric softener 1.7 L')}/></label>
    <label>{t('Kategória','Category')}<input value={form.category} onChange={change('category')}/></label>
    <label>{t('Termék / ajánlat URL','Product / offer URL')}<input type="url" value={form.supplier_url} onChange={change('supplier_url')} placeholder="https://..."/></label>
    <label>{t('MOQ megnevezése','MOQ label')}<input value={form.moq_label} onChange={change('moq_label')} placeholder={t('2 kamion / 66 raklap','2 truckloads / 66 pallets')}/></label>
    <label>{t('Célmennyiség','Target quantity')}<input required type="number" min="0.001" step="0.001" value={form.target_quantity} onChange={change('target_quantity')}/></label>
    <label>{t('Foglalási / MOQ egység','Reservation / MOQ unit')}<input value={form.unit} onChange={change('unit')} placeholder={t('raklap, karton, kg, db','pallet, carton, kg, pcs')}/></label>
    <label>{t('Minimum csatlakozás','Minimum participation')}<input required type="number" min="0.001" step="0.001" value={form.min_join_quantity} onChange={change('min_join_quantity')}/></label>
    <label>{t('Fix ár','Fixed price')}<input required type="number" min="0.0001" step="0.0001" value={form.unit_price} onChange={change('unit_price')}/></label>
    <label>{t('Áregység','Price unit')}<input required value={form.price_unit} onChange={change('price_unit')} placeholder={t('karton, db, kg, raklap','carton, pcs, kg, pallet')}/></label>
    <label>{t('Áregység / 1 foglalási egység','Price units per 1 reservation unit')}<input required type="number" min="0.001" step="0.001" value={form.price_units_per_order_unit} onChange={change('price_units_per_order_unit')}/><small>{t('Példa: 60 karton / raklap → 60','Example: 60 cartons / pallet → 60')}</small></label>
    <label>{t('Pénznem','Currency')}<select value={form.currency} onChange={change('currency')}><option>EUR</option><option>HUF</option><option>PLN</option><option>RON</option><option>CZK</option></select></label>
    <label>{t('Célország','Destination country')}<input value={form.destination_country} onChange={change('destination_country')}/></label>
    <label>{t('Jelentkezési határidő','Participation deadline')}<input type="datetime-local" value={form.deadline} onChange={change('deadline')}/></label>
   </div>
   <div className="bp-fixed-price-note">{t('Az itt megadott egységár a teljes kampány alatt fix. Az üzlet csak akkor indul el, ha a közös foglalások elérik az MOQ-t.','The unit price entered here stays fixed for the full campaign. The deal proceeds only when combined commitments reach the MOQ.')}</div>
   <label>{t('Termékleírás','Product description')}<textarea value={form.product_description} onChange={change('product_description')} placeholder={t('Kiszerelés, karton- és raklaptartalom, szállítás, minőség, eredet...','Pack size, carton/pallet content, shipping, quality, origin...')}/></label>
   <label>{t('Megjegyzés az adminnak','Note to admin')}<textarea value={form.notes} onChange={change('notes')}/></label>
   <button className="button" disabled={busy}>{busy?<LoaderCircle className="spin" size={17}/>:<Plus size={17}/>} {t('Ajánlat beküldése','Submit offer')}</button>
  </form>
  {error&&<div className="error-box">{error}</div>}{message&&<div className="run-report">{message}</div>}
  <section className="manufacturer-panel"><div className="manufacturer-toolbar"><div><strong>{t('Saját közös beszerzési ajánlataim','My Group Order offers')}</strong><small>{t('A DRAFT státusz admin-jóváhagyásra vár.','DRAFT status means the offer is awaiting admin approval.')}</small></div><button className="icon-button" type="button" onClick={()=>void load()} aria-label={t('Frissítés','Refresh')}><RefreshCw size={17}/></button></div>{loading?<div className="empty-state"><LoaderCircle className="spin"/></div>:items.length===0?<div className="empty-state">{t('Még nem küldtél be nagy MOQ ajánlatot.','You have not submitted a high-MOQ offer yet.')}</div>:<div className="group-order-grid">{items.map(order=><article className="group-order-card" key={order.id}><div className="group-order-card-head"><div><span className={`group-status status-${order.status.toLowerCase()}`}>{order.status}</span><h3>{order.title}</h3><p>{order.brand&&<strong>{order.brand} · </strong>}{order.product_name}</p>{order.product_description&&<p className="group-order-description">{order.product_description}</p>}</div><ShoppingCart/></div><GroupOrderProgress reserved={order.reserved_quantity} target={order.target_quantity} unit={order.unit} percentage={order.fill_percentage} locale={locale}/><div className="group-meta-grid"><div><span>MOQ</span><strong>{order.moq_label||formatQuantity(order.target_quantity,order.unit,locale)}</strong></div><div><span>{t('Minimum','Minimum')}</span><strong>{formatQuantity(order.min_join_quantity,order.unit,locale)}</strong></div><div><span>{t('Áregység / foglalási egység','Price units / reservation unit')}</span><strong>{order.price_units_per_order_unit} {displayUnit(order.price_unit,locale)} / {displayUnit(order.unit,locale)}</strong></div><div><span>{t('Fix ár','Fixed price')}</span><strong>{formatMoney(order.unit_price,order.currency,locale)} / {displayUnit(order.price_unit,locale)}</strong></div><div><span>{t('Résztvevők','Participants')}</span><strong>{order.participants} {t('cég','companies')}</strong></div></div><div className="group-card-actions"><button className="button button-small button-ghost" type="button" onClick={()=>void requestBoost(order.id)}>{t('Kiemelés 7 napra','Boost for 7 days')}</button><Link className="button button-small button-ghost" href="/supplier/billing">{t('További fizetős funkciók','More paid features')}</Link></div></article>)}</div>}</section>
 </>;
}
