import {NextRequest,NextResponse} from 'next/server';
import {getRequestSession} from '@/lib/auth-server';
import {serviceSelect,serviceWrite} from '@/lib/supabase-rest';
import {audit,trackEvent} from '@/lib/audit';
import {getPlatformSettings} from '@/lib/platform-settings';
const t=(v:any)=>String(v??'').trim();
export async function GET(request:NextRequest){const ps=await getPlatformSettings();if(!ps.support_enabled)return NextResponse.json({tickets:[],disabled:true});const s=await getRequestSession(request);if(!s)return NextResponse.json({error:'Unauthorized'},{status:401});const tickets=await serviceSelect<any[]>(`support_tickets?created_by=eq.${s.user.id}&select=*&order=created_at.desc&limit=100`).catch(()=>[]);const ids=tickets.map(x=>x.id);const messages=ids.length?await serviceSelect<any[]>(`support_ticket_messages?ticket_id=in.(${ids.join(',')})&internal=eq.false&select=*&order=created_at.asc`).catch(()=>[]):[];return NextResponse.json({tickets:tickets.map(ticket=>({...ticket,messages:messages.filter(m=>m.ticket_id===ticket.id)}))})}
export async function POST(request:NextRequest){const ps=await getPlatformSettings();if(!ps.support_enabled)return NextResponse.json({error:'Support is currently disabled.'},{status:503});const s=await getRequestSession(request);if(!s)return NextResponse.json({error:'Unauthorized'},{status:401});const b=await request.json().catch(()=>({}));const action=t(b.action||'CREATE').toUpperCase();if(action==='REPORT'){const targetType=t(b.target_type).toUpperCase(),targetId=t(b.target_id),reason=t(b.reason);if(!targetType||!targetId||!reason)return NextResponse.json({error:'Missing report data.'},{status:400});const rows=await serviceWrite<any[]>('moderation_reports',{method:'POST',body:JSON.stringify({reporter_id:s.user.id,target_type:targetType,target_id:targetId,reason,details:t(b.details),status:'OPEN'})});await audit(s.user.id,'MODERATION_REPORT_CREATED',targetType,targetId,{report_id:rows?.[0]?.id,reason});return NextResponse.json({report:rows?.[0]||null})}
if(action==='REPLY'){const ticketId=t(b.ticket_id),body=t(b.body);if(!ticketId||!body)return NextResponse.json({error:'Ticket and message required.'},{status:400});const [ticket]=await serviceSelect<any[]>(`support_tickets?id=eq.${encodeURIComponent(ticketId)}&created_by=eq.${s.user.id}&select=id,status&limit=1`).catch(()=>[]);if(!ticket)return NextResponse.json({error:'Ticket not found.'},{status:404});const rows=await serviceWrite<any[]>('support_ticket_messages',{method:'POST',body:JSON.stringify({ticket_id:ticketId,sender_id:s.user.id,body,internal:false})});await serviceWrite(`support_tickets?id=eq.${ticketId}`,{method:'PATCH',body:JSON.stringify({status:ticket.status==='WAITING_USER'?'IN_PROGRESS':ticket.status,updated_at:new Date().toISOString()})});await trackEvent(s.user.id,s.profile.role,'SUPPORT_REPLY','SUPPORT_TICKET',ticketId,{});return NextResponse.json({message:rows?.[0]||null})}
const subject=t(b.subject),body=t(b.body);if(!subject||!body)return NextResponse.json({error:'Subject and message required.'},{status:400});const category=t(b.category||'GENERAL').toUpperCase();const priority=['LOW','NORMAL','HIGH','URGENT'].includes(t(b.priority).toUpperCase())?t(b.priority).toUpperCase():'NORMAL';const rows=await serviceWrite<any[]>('support_tickets',{method:'POST',body:JSON.stringify({created_by:s.user.id,role:s.profile.role,subject,category,priority,status:'OPEN'})});const ticket=rows?.[0];if(ticket)await serviceWrite('support_ticket_messages',{method:'POST',body:JSON.stringify({ticket_id:ticket.id,sender_id:s.user.id,body,internal:false})});await trackEvent(s.user.id,s.profile.role,'SUPPORT_TICKET_CREATED','SUPPORT_TICKET',ticket?.id||null,{category,priority});await audit(s.user.id,'SUPPORT_TICKET_CREATED','SUPPORT_TICKET',ticket?.id||null,{category,priority});return NextResponse.json({ticket})}
