import { NextRequest,NextResponse } from 'next/server';
import { getRequestSession } from '@/lib/auth-server';
import { serviceSelect,serviceWrite } from '@/lib/supabase-rest';
import { audit,trackEvent } from '@/lib/audit';
const arr=(v:any)=>Array.isArray(v)?v.map(String).map(x=>x.trim()).filter(Boolean):String(v||'').split(',').map(x=>x.trim()).filter(Boolean);
export async function GET(request:NextRequest){const s=await getRequestSession(request);if(!s)return NextResponse.json({error:'Unauthorized'},{status:401});const manufacturer=s.profile.role==='MANUFACTURER'?(await serviceSelect<any[]>(`manufacturer_profiles?id=eq.${s.user.id}&select=*&limit=1`).catch(()=>[]))[0]||null:null;return NextResponse.json({profile:s.profile,manufacturer})}
export async function PATCH(request:NextRequest){const s=await getRequestSession(request);if(!s)return NextResponse.json({error:'Unauthorized'},{status:401});const b=await request.json().catch(()=>({}));const complete=Boolean(b.complete);const profilePatch:any={full_name:String(b.full_name||s.profile.full_name||'').trim(),company_name:String(b.company_name||s.profile.company_name||'').trim(),phone:String(b.phone||'').trim()||null,country:String(b.country||'').trim()||null,website:String(b.website||'').trim()||null,business_type:String(b.business_type||'').trim()||null,preferred_categories:arr(b.preferred_categories),preferred_countries:arr(b.preferred_countries),annual_purchase_volume:String(b.annual_purchase_volume||'').trim()||null,sourcing_notes:String(b.sourcing_notes||'').trim()||null,onboarding_step:Math.max(0,Math.min(5,Number(b.onboarding_step)||0)),onboarding_completed:complete,updated_at:new Date().toISOString()};await serviceWrite(`profiles?id=eq.${s.user.id}`,{method:'PATCH',body:JSON.stringify(profilePatch)});
if(s.profile.role==='MANUFACTURER'){const mp:any={id:s.user.id,supplier_type:['MANUFACTURER','WHOLESALER','BOTH'].includes(String(b.supplier_type||'').toUpperCase())?String(b.supplier_type).toUpperCase():'MANUFACTURER',description:String(b.description||'').trim(),website:String(b.website||'').trim()||null,categories:arr(b.preferred_categories),production_countries:arr(b.production_countries),small_batch:Boolean(b.small_batch),large_batch:Boolean(b.large_batch),moq_text:String(b.moq_text||'').trim()||null,updated_at:new Date().toISOString()};await serviceWrite('manufacturer_profiles?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(mp)}).catch(()=>null)}
await trackEvent(s.user.id,s.profile.role,complete?'ONBOARDING_COMPLETED':'ONBOARDING_UPDATED','PROFILE',s.user.id,{step:profilePatch.onboarding_step});await audit(s.user.id,complete?'ONBOARDING_COMPLETED':'ONBOARDING_UPDATED','PROFILE',s.user.id,{step:profilePatch.onboarding_step});return NextResponse.json({success:true,complete})}
