'use client';
import Link from 'next/link';
import { useState } from 'react';
import { Building2, LoaderCircle, LockKeyhole, UserRound } from 'lucide-react';
import type { UserRole } from '@/lib/auth-types';
import type { Locale } from '@/lib/i18n-shared';
import LanguageSwitcher from '@/components/LanguageSwitcher';

type Props = { mode: 'login' | 'register'; role: UserRole; title: string; subtitle: string; locale?: Locale };

const countries = [
  ['Hungary','Magyarország','Hungary'],['Bulgaria','Bulgária','Bulgaria'],['Poland','Lengyelország','Poland'],['Romania','Románia','Romania'],['Czech Republic','Csehország','Czech Republic'],['Slovakia','Szlovákia','Slovakia'],['Croatia','Horvátország','Croatia'],['Slovenia','Szlovénia','Slovenia'],['Lithuania','Litvánia','Lithuania'],['Latvia','Lettország','Latvia'],['Estonia','Észtország','Estonia'],
];

export default function AuthForm({ mode, role, title, subtitle, locale='hu' }: Props) {
  const en=locale==='en'; const t=(hu:string,enText:string)=>en?enText:hu;
  const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  const [form,setForm]=useState({email:'',password:'',fullName:'',companyName:'',phone:'',country:'Hungary',website:'',supplierType:'MANUFACTURER'});
  const isRegister=mode==='register'; const update=(key:keyof typeof form,value:string)=>setForm(current=>({...current,[key]:value}));
  async function submit(event:React.FormEvent){event.preventDefault();setLoading(true);setError('');setMessage('');try{const endpoint=isRegister?'/api/auth/register':'/api/auth/login';const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(isRegister?{...form,role}:{email:form.email,password:form.password,expectedRole:role})});const text=await response.text();let data:any={};try{data=text?JSON.parse(text):{}}catch{data={error:text}}if(!response.ok)throw new Error(data.error||t('A művelet sikertelen.','The operation failed.'));if(data.needsEmailConfirmation){setMessage(t('A regisztráció elkészült. Ellenőrizd az e-mail-fiókodat, majd jelentkezz be.','Registration completed. Check your email, then log in.'))}else{const requestedNext=new URLSearchParams(window.location.search).get('next')||'';const safeNext=requestedNext.startsWith('/')&&!requestedNext.startsWith('//')?requestedNext:'';window.location.href=safeNext||data.redirectTo}}catch(err){setError(err instanceof Error?err.message:t('Ismeretlen hiba.','Unknown error.'))}finally{setLoading(false)}}
  const loginHref=role==='ADMIN'?'/admin/login':role==='MANUFACTURER'?'/supplier/login':'/buyer/login'; const registerHref=role==='MANUFACTURER'?'/supplier/register':'/buyer/register';
  const portalLabel=role==='ADMIN'?t('ADMIN FELÜLET','ADMIN PORTAL'):role==='MANUFACTURER'?t('BESZÁLLÍTÓI PORTÁL','SUPPLIER PORTAL'):t('VEVŐI PORTÁL','BUYER PORTAL');
  return <main className="auth-page"><section className="auth-card"><div className="auth-card-tools"><Link href="/" className="brand auth-brand bulkpact-brand"><span className="bulkpact-mark">BP</span><strong>BulkPact</strong></Link><LanguageSwitcher locale={locale} compact/></div><div className="auth-icon">{role==='ADMIN'?<LockKeyhole/>:role==='MANUFACTURER'?<Building2/>:<UserRound/>}</div><p className="eyebrow">{portalLabel}</p><h1>{title}</h1><p className="auth-subtitle">{subtitle}</p>
    <form onSubmit={submit} className="auth-form">{isRegister&&<><label>{t('Kapcsolattartó neve','Contact person')}<input required value={form.fullName} onChange={e=>update('fullName',e.target.value)} autoComplete="name"/></label><label>{t('Cégnév','Company name')}<input required value={form.companyName} onChange={e=>update('companyName',e.target.value)}/></label><div className="form-grid"><label>{t('Ország','Country')}<select value={form.country} onChange={e=>update('country',e.target.value)}>{countries.map(([value,hu,enLabel])=><option value={value} key={value}>{en?enLabel:hu}</option>)}</select></label><label>{t('Telefonszám','Phone')}<input value={form.phone} onChange={e=>update('phone',e.target.value)} autoComplete="tel"/></label></div>{role==='MANUFACTURER'&&<><label>{t('Cégtípus','Company type')}<select value={form.supplierType} onChange={e=>update('supplierType',e.target.value)}><option value="MANUFACTURER">{t('Gyártó','Manufacturer')}</option><option value="WHOLESALER">{t('Nagykereskedő / disztribútor','Wholesaler / distributor')}</option><option value="BOTH">{t('Gyártó és nagykereskedő','Manufacturer and wholesaler')}</option></select></label><label>{t('Weboldal','Website')}<input value={form.website} onChange={e=>update('website',e.target.value)} placeholder="https://"/></label></>}</>}
      <label>{t('E-mail-cím','Email address')}<input type="email" required value={form.email} onChange={e=>update('email',e.target.value)} autoComplete="email"/></label><label>{t('Jelszó','Password')}<input type="password" minLength={8} required value={form.password} onChange={e=>update('password',e.target.value)} autoComplete={isRegister?'new-password':'current-password'}/></label>{error&&<div className="run-error">{error}</div>}{message&&<div className="run-report">{message}</div>}<button className="button auth-submit" disabled={loading}>{loading&&<LoaderCircle className="spin" size={18}/>} {isRegister?t('Regisztráció','Register'):t('Bejelentkezés','Log in')}</button></form>
    {role!=='ADMIN'&&<p className="auth-switch">{isRegister?t('Már van fiókod?','Already have an account?'):t('Még nincs fiókod?','No account yet?')} <Link href={isRegister?loginHref:registerHref}>{isRegister?t('Jelentkezz be','Log in'):t('Regisztrálj','Register')}</Link></p>}<Link className="auth-back" href="/">← {t('Vissza a főoldalra','Back to home')}</Link></section></main>;
}
